sudo: false
language: node_js
node_js:
  - 6
  - 7

notifications:
  slack:
    - secure: "XcPe6KEKMb2ABO3pjyw4Yh2xe8caiSxbkCiqd9N939LcOFgdejfkSSc6YmoxQps96d2pEBaRPUOgc1uxKtftSQM+Efm9fnahZYUAyWTwhSatZu508/ykUNRE+bLxL6UzT7oM880Hd2j5jtwNf1hbR6BEgJTxOiQJCbXoX2qrUf6AwBQeEsVrI+gPvbxrKOKHF7Yv5mFR3XKokb1llgHEKqGWVmzdrbaOOQvyJ6HrE+hRrGK9SKuJLdQzv4bxF3azxVOKWxus5uevH+5Ux9vqyqLMEdzruXcSdd7uMS+XoyECWWvBXZ0RcTFi5YcTPCxw7YUnu94y6VyMhXY6XkDRjUhK3RpOqZM4ugqGawCfeef9SRpxIvbdpvj4v2Dj23yHDTljeIYKvBLRh8Zv46CdNPrTPI/t6C0AwJ/2nvSXlBiHl488w8ZK0Ft7nSAR/4ZAC2A17otQ13+f7UtGnhjUCrxGS+sTRogPGl7b5xo/bLkwaBmblo4AGAxHvnCi7G6Kejj2TuhjARUs3xRo+OTfScoiArAfUymOy18sasahaBW1RfBm6x2j4t18SOuAqsAnL2kG5K/nb7lcUzQ+qXIMsBaN6jpYpx54Xk9r6rZjVkBcjfrwdZ2H/kxqB/iLGA1YfYmqNwzqXvp8h2QC91NpjYUM7Zgk093wSsMP1j1XgKU="
